Repository mitodl/bootcamp-ecommerce, pull requests merged in 2020-05, with the labels that each got.

#452 Fix environment variable for USE_S3, and remove reference to removed OverwriteStorage
  app.json
  main/settings.py
Labels: Needs Review

#433 asadiqbal08/added resource pages in CMS
  cms/blocks.py
  cms/migrations/0002_resourcepage.py
  cms/models.py
  cms/templates/resource_template.html
  main/templates/base.html
  package.json
  static/images/resource-page-banner-bg.png
  static/scss/_variables.scss
  static/scss/layout.scss
  static/scss/resource.scss
  yarn.lock
Labels: Needs Review

#446 Added bootcamp application models and admin
  applications/__init__.py
  applications/admin.py
  applications/apps.py
  applications/constants.py
  applications/migrations/0001_bootcamp_application_models.py
  applications/migrations/__init__.py
  applications/models.py
  applications/models_test.py
  klasses/admin.py
  main/settings.py
  main/utils.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#432 update sentry sdk
  main/celery.py
  main/sentry.py
  main/settings.py
  main/templates/500.html
  main/templates/base.html
  main/views.py
  main/views_test.py
  main/wsgi.py
  package.json
  requirements.in
  requirements.txt
  static/js/entry/sentry_client.js
  yarn.lock
Labels: Needs Review

#456 Fix allowed hosts env var
  main/envs.py
  main/envs_test.py
Labels: Waiting on Author

#455 asadiqbal08/Basic Bootcamp Run Page
  cms/migrations/0003_bootcamp_product_run_page.py
  cms/models.py
  cms/templates/product_page.html
  main/settings.py
  main/urls.py
Labels: Waiting on Author

#444 Initial work for supporting Jobma
  app.json
  jobma/__init__.py
  jobma/admin.py
  jobma/api.py
  jobma/api_test.py
  jobma/apps.py
  jobma/factories.py
  jobma/migrations/0001_initial.py
  jobma/migrations/__init__.py
  jobma/models.py
  jobma/permissions.py
  jobma/permissions_test.py
  jobma/urls.py
  jobma/views.py
  jobma/views_test.py
  main/settings.py
  main/urls.py
Labels: Waiting on Author

#454 Renamed the 'Klass' model and various code references
  applications/models.py
  cms/migrations/0004_rename_klass_to_bootcamp_run.py
  cms/models.py
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/factories.py
  ecommerce/migrations/0004_rename_klass_to_bootcamp_run.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  fluidreview/api.py
  fluidreview/api_test.py
  fluidreview/views_test.py
  hubspot/serializers.py
  hubspot/serializers_test.py
  hubspot/task_helpers.py
  klasses/admin.py
  klasses/api.py
  klasses/api_test.py
  klasses/apps.py
  klasses/bootcamp_admissions_client.py
  klasses/bootcamp_admissions_client_test.py
  klasses/conftest.py
  klasses/factories.py
  klasses/migrations/0015_rename_klass_to_bootcamp_run.py
  klasses/models.py
  klasses/models_test.py
  klasses/permissions.py
  klasses/serializers.py
  klasses/urls.py
  klasses/views.py
  klasses/views_test.py
  main/templates/bootcamp/statement.html
  smapply/api.py
  smapply/api_test.py
  smapply/views_test.py
  static/js/actions/index.js
  static/js/actions/index_test.js
  static/js/components/Payment.js
  static/js/components/PaymentHistory.js
  static/js/components/PaymentHistory_test.js
  static/js/components/Payment_test.js
  static/js/containers/PaymentPage.js
  static/js/containers/PaymentPage_test.js
  static/js/factories/index.js
  static/js/flow/bootcampTypes.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/bootcamps.js
  static/js/lib/queries/index.js
  static/js/lib/queries/klasses.js
  static/js/reducers/ui.js
  static/js/reducers/ui_test.js
  static/js/util/util.js
  static/js/util/util_test.js
Labels: Waiting on Author

#469 Fixed 'Klass' reference in jobma app
  jobma/apps.py
  jobma/factories.py
  jobma/migrations/0002_rename_klass.py
  jobma/models.py
  klasses/migrations/0015_rename_klass_to_bootcamp_run.py
Labels: Waiting on Author

#422 pre-commit hooks
  .pre-commit-config.yaml
  .secrets.baseline
  README.md
Labels: Needs Review

#461 Application model and admin fixes
  applications/admin.py
  applications/factories.py
  applications/migrations/0002_minor_fixes.py
  applications/models.py
  applications/models_test.py
  main/models.py
Labels: Waiting on Author

#473 Pin ddt dependency
  test_requirements.txt
Labels: Needs Review

#475 Moved application submission review fields
  applications/constants.py
  applications/factories.py
  applications/migrations/0003_move_review_fields.py
  applications/models.py
Labels: Waiting on Author

#467 Header section for product page - #441
  .gitignore
  cms/migrations/0005_product_page_header.py
  cms/migrations/0006_remove_bootcamprunpage_content.py
  cms/models.py
  cms/templates/product_page.html
  static/scss/cms/product.scss
  static/scss/layout.scss
Labels: Waiting on Author

#480 Convert all tests to pytest
  authentication/views_test.py
  backends/edxorg_test.py
  backends/pipeline_api_test.py
  backends/utils_test.py
  ecommerce/admin_test.py
  ecommerce/api_test.py
  ecommerce/models_test.py
  ecommerce/serializers_test.py
  ecommerce/views_test.py
  fixtures/common.py
  mail/api_test.py
  main/serializers_test.py
  main/templatetags/render_bundle_test.py
  main/urls_test.py
  pytest.ini
  smapply/api_test.py
  test_requirements.txt
Labels: Needs Review

#487 Moved templatetags tests out of templatetags module to fix build
  main/templatetags/custom_tag_test.py
  main/templatetags_test.py
Labels: Waiting on Author

#489 Fix Jobma webhook permissions check
  jobma/permissions.py
  jobma/permissions_test.py
Labels: Needs Review

#484 Added internal API for starting applications and setting correct state
  app.json
  applications/api.py
  applications/api_test.py
  applications/management/__init__.py
  applications/management/commands/__init__.py
  applications/management/commands/set_application_state.py
  applications/models.py
  conftest.py
  main/settings.py
Labels: Waiting on Author

#495 Fix accidental removal of pylint from pytest.ini
  backends/utils_test.py
  ecommerce/api_test.py
  ecommerce/models_test.py
  ecommerce/serializers_test.py
  mail/api_test.py
  main/serializers_test.py
  main/templatetags_test.py
  pytest.ini
  smapply/api_test.py
Labels: Waiting on Author

#459 Update hubspot contact sync code
  app.json
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  hubspot/api.py
  hubspot/api_test.py
  hubspot/management/commands/configure_hubspot_bridge.py
  hubspot/management/commands/sync_hubspot.py
  hubspot/serializers.py
  hubspot/serializers_test.py
  hubspot/task_helpers.py
  hubspot/tasks.py
  hubspot/tasks_test.py
  main/settings.py
  profiles/serializers.py
  profiles/serializers_test.py
  smapply/api.py
  smapply/tasks.py
  smapply/tasks_test.py
Labels: Waiting on Author

#488 Profile adjustments
  authentication/serializers.py
  hubspot/management/commands/configure_hubspot_bridge.py
  profiles/migrations/0009_remove_profile_leadership_level.py
  profiles/models.py
  profiles/serializers.py
  profiles/views_test.py
  static/js/components/forms/EditProfileForm.js
  static/js/components/forms/EditProfileForm_test.js
  static/js/components/forms/ProfileFormFields.js
  static/js/components/forms/RegisterDetailsForm.js
  static/js/components/forms/RegisterExtraDetailsForm.js
  static/js/constants.js
  static/js/factories/user.js
  static/js/flow/authTypes.js
  static/js/lib/validation.js
  static/js/pages/profile/ViewProfilePage.js
Labels: Waiting on Author

#503 add basic drawer component
  .flowconfig
  package.json
  static/js/Router.js
  static/js/components/Drawer.js
  static/js/components/Drawer_test.js
  static/js/pages/App.js
  static/js/reducers/drawer.js
  static/js/reducers/index.js
  static/js/util/withTracker.js
  static/scss/drawer.scss
  static/scss/layout.scss
  yarn.lock
Labels: Waiting on Author

#496 Add support for interview_link from Jobma
  jobma/api.py
  jobma/api_test.py
  jobma/factories.py
  jobma/migrations/0003_add_interview_link.py
  jobma/models.py
Labels: Waiting on Author

#472 product page: add faculty section
  cms/blocks.py
  cms/migrations/0007_instructorspage.py
  cms/models.py
  cms/templates/partials/instructor.html
  cms/templates/product_page.html
  cms/templatetags/__init__.py
  cms/templatetags/image_version_url.py
  main/templates/base.html
  main/urls.py
  main/views_test.py
  package.json
  static/fonts/icomoon.eot
  static/fonts/icomoon.svg
  static/fonts/icomoon.ttf
  static/fonts/icomoon.woff
  static/js/entry/third-party.js
  static/scss/_variables.scss
  static/scss/cms/instructor.scss
  static/scss/icomoon.scss
  static/scss/layout.scss
  static/scss/slick.scss
  webpack.config.shared.js
  yarn.lock
Labels: Needs Review

#465 asadiqbal08/backend + Frontend changes for Learning Area Page
  cms/blocks.py
  cms/migrations/0008_column_image_text_section.py
  cms/models.py
  cms/templates/partials/three-column-image-text-section.html
  cms/templates/product_page.html
  main/urls.py
  static/scss/cms/three-column-image-section.scss
  static/scss/layout.scss
Labels: Waiting on Author

#497 Add support for uploading a resume to an existing application
  applications/api.py
  applications/api_test.py
  applications/exceptions.py
  applications/migrations/0004_bootcampapplication_resume_upload_date.py
  applications/models.py
  applications/models_test.py
  applications/utils.py
Labels: Waiting on Author

#486 Bootcamp enrollments models
  applications/models.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  klasses/migrations/0016_bootcamprunenrollment.py
  klasses/models.py
Labels: Waiting on Author

#508 Redirect user to detail form if no legal address
  .pre-commit-config.yaml
  applications/api_test.py
  authentication/pipeline/compliance.py
  authentication/pipeline/compliance_test.py
  authentication/pipeline/conftest.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  profiles/constants.py
  profiles/factories.py
  profiles/models.py
  profiles/models_test.py
Labels: Waiting on Author

#505 Fix duplicate color variable
  static/scss/_variables.scss
  static/scss/payment.scss
Labels: Waiting on Author

#507 Added endpoint for fetching detailed user application data
  applications/admin.py
  applications/api.py
  applications/api_test.py
  applications/constants.py
  applications/factories.py
  applications/migrations/0005_application_multiple_orders.py
  applications/migrations/0006_change_submission_types.py
  applications/models.py
  applications/models_test.py
  applications/serializers.py
  applications/serializers_test.py
  applications/urls.py
  applications/views.py
  applications/views_test.py
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/factories.py
  ecommerce/migrations/0005_application_multiple_orders.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/urls.py
  ecommerce/views_test.py
  klasses/serializers.py
  main/permissions.py
  main/test_utils.py
  main/urls.py
  main/utils.py
  main/utils_test.py
Labels: Waiting on Author

#515 Fix support links
  app.json
  main/settings.py
  main/templates/404.html
  main/templates/500.html
  main/views.py
  main/views_test.py
  static/js/flow/declarations.js
  static/js/pages/login/LoginForgotPasswordPage.js
  static/js/pages/login/LoginForgotPasswordPage_test.js
  static/js/pages/register/RegisterConfirmSentPage.js
  static/js/pages/register/RegisterConfirmSentPage_test.js
  static/js/pages/register/RegisterDeniedPage.js
  static/js/pages/register/RegisterDeniedPage_test.js
  static/js/pages/register/RegisterErrorPage.js
  static/js/pages/register/RegisterErrorPage_test.js
Labels: Waiting on Author

#517 Fix registration profile form validation
  static/js/components/forms/EditProfileForm.js
  static/js/components/forms/EditProfileForm_test.js
  static/js/components/forms/RegisterExtraDetailsForm.js
  static/js/factories/user.js
  static/js/pages/profile/EditProfilePage.js
  static/js/pages/profile/EditProfilePage_test.js
Labels: Work in progress

#518 Added endpoint for fetching list of user applications
  applications/serializers.py
  applications/serializers_test.py
  applications/views.py
  applications/views_test.py
Labels: Waiting on Author

#525 Move ecommerce-related views into ecommerce app
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/urls.py
  ecommerce/views.py
  ecommerce/views_test.py
  klasses/api.py
  klasses/api_test.py
  klasses/urls.py
  klasses/views.py
  klasses/views_test.py
  main/urls.py
Labels: Waiting on Author

#530 Remove duplicate function
  static/js/lib/api/util.js
  static/js/lib/redux_query.js
Labels: Needs Review

#502 Minimal site topnav - #436
  cms/templates/product_page.html
  main/templates/base.html
  main/templates/top_nav.html
  package.json
  static/js/entry/third-party.js
  static/scss/cms/topnav.scss
  static/scss/layout.scss
  webpack.config.shared.js
  yarn.lock
Labels: Waiting on Author

#532 Added endpoint to create a bootcamp application
  applications/api.py
  applications/api_test.py
  applications/serializers.py
  applications/serializers_test.py
  applications/views.py
  applications/views_test.py
Labels: Waiting on Author

#536 Fixed application list view to only return applications that belong to the logged-in user
  applications/views.py
  applications/views_test.py
Labels: Waiting on Author

#540 Added newrelic to worker processes
  Procfile
Labels: Waiting on Author

#534 Add API for available bootcamp runs
  klasses/serializers.py
  klasses/serializers_test.py
  klasses/urls.py
  klasses/views.py
  klasses/views_test.py
  main/urls.py
Labels: Waiting on Author

#526 Add API for submitting review for application submissions
  applications/api.py
  applications/api_test.py
  applications/models.py
  applications/models_test.py
  applications/urls.py
  applications/views.py
  applications/views_test.py
Labels: Waiting on Author

#528 Add checkout data API
  applications/api.py
  applications/constants.py
  applications/models.py
  applications/models_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/test_utils.py
  ecommerce/urls.py
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Needs Review

#553 Updated overall site styling
  main/templates/navbar.html
  static/images/mit_logo.svg
  static/scss/_inputs.scss
  static/scss/_shared.scss
  static/scss/_variables.scss
  static/scss/auth.scss
  static/scss/landing.scss
  static/scss/layout.scss
  static/scss/payment.scss
  static/scss/user-menu.scss
Labels: Waiting on Author

#541 add site-wide notification
  cms/factories.py
  cms/migrations/0009_sitenotification.py
  cms/model_test.py
  cms/models.py
  main/templates/base.html
  main/templates/partials/notifications.html
  main/templatetags/latest_notification.py
Labels: Needs Review

#546 Refactor hubspot deal/line syncing
  applications/__init__.py
  applications/api.py
  applications/api_test.py
  applications/apps.py
  applications/constants.py
  applications/models.py
  applications/signals.py
  applications/signals_test.py
  ecommerce/views_test.py
  fixtures/common.py
  hubspot/api.py
  hubspot/api_test.py
  hubspot/management/commands/sync_hubspot.py
  hubspot/serializers.py
  hubspot/serializers_test.py
  hubspot/task_helpers.py
  hubspot/task_helpers_test.py
  hubspot/tasks.py
  hubspot/tasks_test.py
Labels: Waiting on Author

#568 Remove redundant routes
  static/js/pages/App.js
Labels: Waiting on Author

#569 Remove ADMISSION_* settings that are not used
  app.json
  main/settings.py
Labels: Waiting on Author

#561 Change PaymentView to accept an application id instead of a run key
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/test_utils.py
  ecommerce/views.py
  ecommerce/views_test.py
  static/js/factories/index.js
  static/js/flow/bootcampTypes.js
  static/js/pages/PaymentPage.js
  static/js/pages/PaymentPage_test.js
Labels: Waiting on Author

#552 Update application state after Jobma webhook
  applications/admin.py
  applications/factories.py
  applications/migrations/0001_bootcamp_application_models.py
  applications/migrations/0007_remove_videofile.py
  applications/models.py
  jobma/constants.py
  jobma/models.py
  jobma/views.py
  jobma/views_test.py
Labels: Waiting on Author

#509 add product page: alumni section
  cms/blocks.py
  cms/migrations/0010_alumnipage.py
  cms/models.py
  cms/templates/partials/alumni.html
  cms/templates/product_page.html
  static/scss/_variables.scss
  static/scss/cms/alumni.scss
  static/scss/layout.scss
Labels: Needs Review

#554 update product page instructors section design
  cms/blocks.py
  cms/migrations/0011_add_banner_field_and_heading_and_heading_singular_to_instructors_section.py
  cms/models.py
  cms/templates/partials/instructor.html
  static/scss/_variables.scss
  static/scss/cms/instructor.scss
  static/scss/slick.scss
Labels: Needs Review

#580 Add results_url from Jobma webhook
  jobma/migrations/0004_interview_results_url.py
  jobma/models.py
  jobma/views.py
  jobma/views_test.py
Labels: Needs Review

#567 Get user info from API on payment page
  main/views.py
  main/views_test.py
  static/js/components/Payment.js
  static/js/components/Payment_test.js
  static/js/flow/authTypes.js
  static/js/flow/declarations.js
  static/js/global_init.js
  static/js/pages/PaymentPage.js
  static/js/pages/PaymentPage_test.js
Labels: Waiting on Author

#578 Added user application dashboard (list view)
  applications/views.py
  applications/views_test.py
  cms/factories.py
  cms/serializers.py
  cms/serializers_test.py
  cms/template_tags_test.py
  klasses/serializers.py
  klasses/serializers_test.py
  main/urls.py
  main/views.py
  main/views_test.py
  pytest.ini
  static/js/components/PaymentHistory_test.js
  static/js/components/Payment_test.js
  static/js/constants.js
  static/js/factories/application.js
  static/js/factories/index.js
  static/js/flow/applicationTypes.js
  static/js/flow/authTypes.js
  static/js/flow/bootcampTypes.js
  static/js/lib/queries/applications.js
  static/js/lib/queries/index.js
  static/js/lib/queries/users.js
  static/js/lib/urls.js
  static/js/pages/App.js
  static/js/pages/PaymentPage.js
  static/js/pages/PaymentPage_test.js
  static/js/pages/applications/ApplicationDashboardPage.js
  static/js/pages/applications/ApplicationDashboardPage_test.js
  static/js/pages/applications/ApplicationPages.js
  static/js/util/util.js
  static/js/util/util_test.js
  static/scss/_shared.scss
  static/scss/application.scss
  static/scss/layout.scss
  test_requirements.txt
Labels: Waiting on Author

#590 Don't error on unexpected arguments in react view
  main/views.py
  main/views_test.py
Labels: Needs Review

#537 Update login/registration UI to match designs
  mail/templates/email_base.html
  main/settings.py
  main/templates/navbar.html
  main/views.py
  package.json
  static/images/bootcamp-logo-black.png
  static/js/components/NotificationContainer.js
  static/js/components/NotificationContainer_test.js
  static/js/components/forms/ChangeEmailForm.js
  static/js/components/forms/ChangePasswordForm.js
  static/js/components/forms/EditProfileForm.js
  static/js/components/forms/EmailForm.js
  static/js/components/forms/LoginPasswordForm.js
  static/js/components/forms/ProfileFormFields.js
  static/js/components/forms/RegisterDetailsForm.js
  static/js/components/forms/RegisterEmailForm.js
  static/js/components/forms/RegisterExtraDetailsForm.js
  static/js/components/forms/ResetPasswordForm.js
  static/js/components/notifications/index.js
  static/js/components/notifications/index_test.js
  static/js/constants.js
  static/js/entry/root.js
  static/js/notifications.js
  static/js/pages/App.js
  static/js/pages/login/LoginForgotPasswordConfirmPage_test.js
  static/js/pages/login/LoginForgotPasswordPage.js
  static/js/pages/profile/EditProfilePage.js
  static/js/pages/profile/ViewProfilePage.js
  static/js/pages/profile/ViewProfilePage_test.js
  static/js/pages/register/RegisterConfirmPage_test.js
  static/js/pages/register/RegisterConfirmSentPage.js
  static/js/pages/register/RegisterConfirmSentPage_test.js
  static/js/pages/register/RegisterDeniedPage.js
  static/js/pages/register/RegisterDetailsPage.js
  static/js/pages/register/RegisterEmailPage.js
  static/js/pages/register/RegisterEmailPage_test.js
  static/js/pages/register/RegisterErrorPage.js
  static/js/pages/register/RegisterExtraDetailsPage.js
  static/js/pages/settings/AccountSettingsPage_test.js
  static/js/pages/settings/EmailConfirmPage_test.js
  static/js/reducers/index.js
  static/js/reducers/notifications.js
  static/js/reducers/notifications_test.js
  static/js/reducers/ui.js
  static/js/reducers/ui_test.js
  static/js/util/util.js
  static/js/util/util_test.js
  static/scss/_inputs.scss
  static/scss/auth.scss
  static/scss/layout.scss
  static/scss/notification.scss
  yarn.lock
Labels: Waiting on Author

#577 Add Linkedin option for resume
  applications/api.py
  applications/api_test.py
  applications/migrations/0008_bootcampapplication_linkedin_url.py
  applications/models.py
  applications/models_test.py
  applications/urls.py
  applications/views.py
  applications/views_test.py
Labels: Waiting on Author
