Repository mitodl/bootcamp-ecommerce, pull requests merged in 2020-07, with the labels that each got.

#855 Added setting for USE_X_FORWARDED_HOST
  app.json
  main/settings.py
Labels: Waiting on Author

#842 Fixed address factory (which caused flaky username test)
  profiles/factories.py
Labels: Waiting on Author, merge after freeze

#864 Added rule to transpile query-string library + dependency
  webpack.config.shared.js
Labels: Waiting on Author

#850 Fixed payment input validation
  static/js/components/PaymentDisplay.js
  static/js/components/PaymentDisplay_test.js
  static/js/lib/queries/ecommerce.js
  static/js/lib/urls.js
Labels: Needs Review

#877 Fixes faulty logic in Profile.is_complete
  main/utils.py
  main/utils_test.py
  profiles/models.py
  profiles/models_test.py
Labels: Waiting on Author

#812 Logo file resize - #808
  static/images/bootcamp-logo-black.png
Labels: Waiting on Author

#828 fix aria-labelledby value for accessiblity issue
  cms/templates/partials/program-description.html
  cms/templates/partials/program-elements.html
Labels: Waiting on Author

#874 Added 'split-on-first' library to loader config
  webpack.config.shared.js
Labels: Waiting on Author

#872 Added min space above footer and made it 'sticky'
  cms/templates/letter_template_page.html
  main/templates/footer.html
  static/scss/layout.scss
Labels: Waiting on Author

#869 Removed ES6 template literal in Django template
  cms/templates/partials/instructor.html
Labels: Waiting on Author

#862 Better formatting for negative formatPrice
  main/templatetags/dollar_format.py
  main/templatetags_test.py
  static/js/util/util.js
  static/js/util/util_test.js
Labels: Waiting on Author

#865 Simplify review submission serializer
  applications/serializers.py
  applications/serializers_test.py
  applications/views.py
  static/js/factories/application.js
  static/js/flow/applicationTypes.js
  static/js/pages/applications/ReviewDashboardPage_test.js
  static/js/pages/applications/ReviewDetailPage.js
  static/js/pages/applications/ReviewDetailPage_test.js
Labels: Waiting on Author

#876 Fix invalid HTML tag
  cms/templates/product_page.html
Labels: Waiting on Author

#867 Attempt to fix undefined hbspt
  main/templates/footer.html
Labels: Waiting on Author

#852 Remove old payment page
  main/settings.py
  main/urls.py
  main/urls_test.py
  static/js/pages/App.js
  static/js/pages/PaymentPage.js
  static/js/pages/PaymentPage_test.js
Labels: Waiting on Author

#890 Fixed sticky footer
  cms/templates/home_page.html
  cms/templates/letter_template_page.html
  cms/templates/product_page.html
  cms/templates/resource_template.html
  main/templates/404.html
  main/templates/500.html
  main/templates/bootcamp/react.html
  static/scss/layout.scss
Labels: Needs Review

#891 Don't prefetch interview which doesn't exist on QuizSubmission
  applications/views.py
  applications/views_test.py
Labels: Waiting on Author

#806 Refund enrollments command
  applications/constants.py
  applications/migrations/0014_application_refund_status.py
  applications/models.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/management/__init__.py
  ecommerce/management/commands/__init__.py
  ecommerce/management/commands/refund_enrollment.py
  hubspot/serializers.py
  klasses/admin.py
  klasses/api.py
  klasses/api_test.py
  klasses/constants.py
  klasses/factories.py
  klasses/migrations/0018_bootcamp_enrollment_status_fields.py
  klasses/models.py
Labels: Waiting on Author

#904 Add application status label for Refunded
  static/js/constants.js
Labels: Waiting on Author

#871 Fix caching for resource page links
  cms/__init__.py
  cms/apps.py
  cms/factories.py
  cms/models.py
  cms/signals.py
  cms/signals_test.py
  cms/utils.py
  cms/utils_test.py
  main/settings.py
Labels: Waiting on Author

#881 cms pages feedback
  cms/templates/partials/three-column-image-text-section.html
  static/scss/_shared.scss
  static/scss/cms/admissions-section.scss
  static/scss/cms/three-column-image-section.scss
  static/scss/layout.scss
Labels: Needs Review

#895 legal address requirement
  applications/api.py
  applications/api_test.py
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/views_test.py
  static/js/factories/user.js
  static/js/flow/authTypes.js
  static/js/pages/applications/ApplicationDashboardPage.js
  static/js/pages/applications/ApplicationDashboardPage_test.js
Labels: Waiting on Author

#910 Allow refunds for users without enrollments (partial payments)
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/management/commands/refund.py
Labels: Waiting on Author

#912 fix dropzone accessibility issue
  static/scss/resume.scss
Labels: Waiting on Author

#905 Paging for submission reviews
  package.json
  static/js/components/SubmissionFacets.js
  static/js/lib/queries/submissions.js
  static/js/pages/applications/ReviewDashboardPage.js
  static/js/pages/applications/ReviewDashboardPage_test.js
  static/scss/layout.scss
  static/scss/submission.scss
  yarn.lock
Labels: Waiting on Author

#897 asadiqbal08/CMS Wagtail Model Tests
  cms/factories.py
  cms/models_test.py
Labels: Waiting on Author

#917 Conditional hubspot/zendesk JS
  main/templates/base.html
  main/templates/footer.html
Labels: Waiting on Author

#906 Implemented consistent error and success behavior
  applications/views.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/urls.py
  ecommerce/views.py
  ecommerce/views_test.py
  main/templates/base.html
  main/utils.py
  main/views.py
  main/views_test.py
  static/js/actions/index.js
  static/js/components/EditProfileDisplay.js
  static/js/components/NewApplication.js
  static/js/components/ResumeLinkedIn.js
  static/js/components/SupportLink.js
  static/js/components/forms/EditProfileForm.js
  static/js/components/notifications/NotificationContainer.js
  static/js/components/notifications/NotificationContainer_test.js
  static/js/components/notifications/index.js
  static/js/constants.js
  static/js/flow/applicationTypes.js
  static/js/flow/authTypes.js
  static/js/flow/ecommerceTypes.js
  static/js/flow/httpTypes.js
  static/js/flow/uiTypes.js
  static/js/global_init.js
  static/js/lib/applicationApi.js
  static/js/lib/applicationApi_test.js
  static/js/lib/queries/applications.js
  static/js/lib/queries/ecommerce.js
  static/js/lib/queries/users.js
  static/js/lib/redux_query.js
  static/js/lib/redux_query_test.js
  static/js/pages/App.js
  static/js/pages/HeaderApp.js
  static/js/pages/applications/ApplicationDashboardPage.js
  static/js/pages/applications/ApplicationDashboardPage_test.js
  static/js/pages/applications/PaymentHistoryPage.js
  static/js/pages/applications/PaymentHistoryPage_test.js
  static/js/reducers/ui.js
  static/js/util/util.js
  static/js/util/util_test.js
  static/scss/_variables.scss
  static/scss/application.scss
  static/scss/notification.scss
  static/scss/slick.scss
Labels: Waiting on Author

#915 fix anchor-tag related accessibility issues on dashboard
  static/js/components/AccessibleAnchor.js
  static/js/components/AccessibleAnchor_test.js
  static/js/components/applications/detail_sections.js
  static/js/components/applications/detail_sections_test.js
  static/js/pages/applications/ApplicationDashboardPage.js
  static/scss/button.scss
  static/scss/layout.scss
Labels: Waiting on Author

#922 Various improvements to django admin classes
  applications/admin.py
  ecommerce/admin.py
  ecommerce/models.py
  ecommerce/models_test.py
  jobma/admin.py
  klasses/admin.py
Labels: Needs Review

#925 fix mobile margin
  static/js/pages/register/RegisterConfirmSentPage.js
  static/js/pages/register/RegisterConfirmSentPage_test.js
  static/scss/auth.scss
Labels: Waiting on Author

#928 More admin improvements, including receipt class fix
  applications/admin.py
  ecommerce/admin.py
Labels: Waiting on Author

#930 Upgrade wagtail - #900
  applications/constants.py
  authentication/pipeline/compliance.py
  authentication/views.py
  cms/management/__init__.py
  cms/management/commands/__init__.py
  cms/management/commands/configure_cms.py
  cms/migrations/0019_create_and_setup_home_page.py
  cms/models.py
  compliance/api.py
  compliance/api_test.py
  ecommerce/api_test.py
  hubspot/api_test.py
  hubspot/management/commands/configure_hubspot_bridge.py
  hubspot/tasks.py
  hubspot/tasks_test.py
  mail/api.py
  profiles/serializers.py
  pylintrc
  requirements.in
  requirements.txt
  test_requirements.txt
Labels: Needs Review

#932 Filter out submissions that cannot be reviewed
  applications/constants.py
  applications/factories.py
  applications/views.py
  applications/views_test.py
Labels: Waiting on Author

#927 Added seed data scripts and commands
  localdev/seed/__init__.py
  localdev/seed/api.py
  localdev/seed/api_test.py
  localdev/seed/config.py
  localdev/seed/deserializers.py
  localdev/seed/management/__init__.py
  localdev/seed/management/commands/__init__.py
  localdev/seed/management/commands/delete_seed_data.py
  localdev/seed/management/commands/seed_data.py
  localdev/seed/resources/seed_data.json
  localdev/seed/utils.py
  main/settings.py
  main/utils.py
  main/utils_test.py
Labels: Needs Review

#939 Updated readme
  .env.example
  README.md
Labels: Waiting on Author

#941 New full_name field for hubspot
  hubspot/management/commands/configure_hubspot_bridge.py
Labels: Waiting on Author

#943 Update the pillow version
  requirements.in
  requirements.txt
Labels: Waiting on Author
