Repository mitodl/bootcamp-ecommerce, pull requests merged in 2021-05, with the labels that each got.

#1215 Upgrade to Python 3.9
  .github/workflows/ci.yml
  Dockerfile
  applications/api.py
  applications/management/utils.py
  hubspot/api.py
  klasses/models.py
  pyproject.toml
  requirements.in
  requirements.txt
  runtime.txt
  test_requirements.txt
Labels: Waiting on Author

#1235 upgrade defusedxml version
  requirements.txt
Labels: Blocked, Waiting on Author, merge after freeze

#1234 Updated bootcamp and order admin classes
  ecommerce/admin.py
  klasses/admin.py
Labels: Blocked, Waiting on Author, merge freeze

#1224 asadiqbal08/Update the merge package
  package.json
  yarn.lock
Labels: Waiting on Author

#1241 Set Application Review => Status to 'Pending' when waitlisting an application
  static/js/components/applications/detail_sections.js
  static/js/components/applications/detail_sections_test.js
Labels: Waiting on Author

#1225 asadiqbal08/version bump property expr
  package.json
  static/js/lib/validation.js
  yarn.lock
Labels: Waiting on Author
